drop table if exists IndCont;
CREATE TABLE IndCont (CMTE_ID, AMNDT_IND, RPT_TP, TRANSACTION_PGI, IMAGE_NUM, TRANSACTION_TP, ENTITY_TP, NAME, CITY, STATE, ZIP_CODE, EMPLOYER, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT INTEGER, OTHER_ID, TRAN_ID, FILE_NUM, MEMO_CD, MEMO_TEXT, SUB_ID);
drop table if exists PacList;
CREATE TABLE PACList(CMTE_ID PRIMARY KEY, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_ST2, CMTE_CITY, CMTE_ST, CMTE_ZIP, CMTE_DSGN, CMTE_TP, CMTE_PTY_AFFILIATION, CMTE_FILING_FREQ, ORG_TP, CONNECTED_ORG_NM, CAND_ID);
drop table if exists Affiliations;
CREATE TABLE Affiliations(CMTE_ID PRIMARY KEY, AFFILIATION INTEGER, NAME, ASSOCIATION);
.separator |
.import itcont.txt IndCont
.import cm.txt PacList
.import affils.txt Affiliations
ALTER TABLE PacList ADD COLUMN AFFILIATION INTEGER DEFAULT 50;
UPDATE PacList SET AFFILIATION = (SELECT Affiliations.AFFILIATION FROM Affiliations WHERE Affiliations.CMTE_ID = PacList.CMTE_ID) WHERE PacList.CMTE_ID in (select CMTE_ID from Affiliations);
ALTER TABLE PacList ADD COLUMN ASSOCIATION;
UPDATE PacList SET ASSOCIATION = (SELECT Affiliations.ASSOCIATION FROM Affiliations WHERE Affiliations.CMTE_ID = PacList.CMTE_ID) WHERE PacList.CMTE_ID in (select CMTE_ID from Affiliations);
